//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

#include<stdio.h>

int main(void)
{
    int i, next;
    long j = 0;
    int n1 = 1;
    int n2 = 2;

    printf("Fibonacci numbers: ");

    while(n1<4000000)
    {
        printf("%i, ", n1);

        next = n1 + n2;
        n1 = n2;
        n2 = next;

        if((n1%2) == 0)
        {
            j += n1;
        }
    }


    printf("\n");
    printf("The sum of the even-valued terms: %li\n", j);   
}
