/*
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include<stdio.h>

long long Tri_number(long long a);
long long div(long long a);

int main(void)
{
    long long value;
    long long number = 1;
    int divisors = 0;
    int x;

    printf("Determine the divisors: ");
    scanf("%i", &x);

    while(divisors<=x)
    {
        value = Tri_number(number);

        divisors = div(value);

        number++;
    }
    printf("First triangle number to have over %i divisors: %lli\n", x, value);
    printf("It's the %lli'th triangle number!\n", number-1);
}

long long Tri_number(long long a)
{
    if(a == 1)
    {
        return 1;
    }
    return a + Tri_number(a-1);
}

long long div(long long a)
{
    int divs = 1;
    int counter;
    for(int i = 2; i <= a; i++)
    {
        counter = 0;
        while((a%i)==0)
        {
            counter++;
            a /= i;
        }
        divs *= counter+1;
        if(a == 1)
        {
            break;
        }
    }
    return divs;
}